config {
  type: "table",
  schema: "gold_marts",
  name: "customer_360"
}

SELECT
  c.customer_id,
  c.customer_city,
  c.customer_state,
  COUNT(DISTINCT o.order_id) AS total_orders,
  SUM(o.total_order_value) AS lifetime_value,
  MIN(o.order_purchase_timestamp) AS first_order_date,
  MAX(o.order_purchase_timestamp) AS last_order_date
FROM ${ref("dim_customers")} c
LEFT JOIN ${ref("fct_orders")} o
ON c.customer_id = o.customer_id
GROUP BY
  c.customer_id,
  c.customer_city,
  c.customer_state